site_name: My Docs
theme: 
  name: material
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

pages:
  - Code Highlight: codehilite.md
  - Tree:
    - One: tree.md
    - Two: 
      - TwoTwo: tree.md
      - Three:
        - Three: tree.md
  - Another: index.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true