site_name: My Docs
theme: 
  name: material
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

pages:
  - Extensions:
    - Code Highlight: codehilite.md
    - Admonition: admonition.md
  - Usages:
    - Admonition: admonition-usage.md
  - Tree:
    - One: tree.md
    - Two: 
      - TwoTwo: tree.md
      - Three:
        - Three: tree.md
  - History: 
    - Home: history.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde